version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
      - image: redis:6
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.15"
      - run:
          command: yarn install
      - run:
          command: yarn run test --runInBand --ci
workflows:
  build-and-test:
    jobs:
      - build-and-test
